// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: t-encoder

#include "../ui.h"

void ui_screen_weather_screen_init(void)
{
ui_screen_weather = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_weather, lv_color_hex(0x140E40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_weather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_temp = lv_label_create(ui_screen_weather);
lv_obj_set_width( ui_Label_temp, 237);
lv_obj_set_height( ui_Label_temp, 104);
lv_obj_set_x( ui_Label_temp, 13 );
lv_obj_set_y( ui_Label_temp, 250 );
lv_obj_set_align( ui_Label_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_temp,"22°");
lv_obj_set_style_text_align(ui_Label_temp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_temp, &ui_font_ZD100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Icon_weather = lv_img_create(ui_screen_weather);
lv_img_set_src(ui_Icon_weather, &ui_img_images_icons_asset_10_png);
lv_obj_set_width( ui_Icon_weather, LV_SIZE_CONTENT);  /// 207
lv_obj_set_height( ui_Icon_weather, LV_SIZE_CONTENT);   /// 148
lv_obj_set_x( ui_Icon_weather, 300 );
lv_obj_set_y( ui_Icon_weather, 0 );
lv_obj_set_align( ui_Icon_weather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_weather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_date = lv_label_create(ui_screen_weather);
lv_obj_set_width( ui_Label_date, 237);
lv_obj_set_height( ui_Label_date, 40);
lv_obj_set_x( ui_Label_date, 0 );
lv_obj_set_y( ui_Label_date, -220 );
lv_obj_set_align( ui_Label_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_date,"6 WED");
lv_obj_set_style_text_color(ui_Label_date, lv_color_hex(0xFE5D0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_ZD30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_screen_weather, ui_event_screen_weather, LV_EVENT_ALL, NULL);

}
