// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: t-encoder

#include "../ui.h"

void ui_screen_menu_screen_init(void)
{
ui_screen_menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_menu, lv_color_hex(0x140E40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_menu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_screen_menu);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 390);
lv_obj_set_height( ui_Container1, 390);
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Container1, LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_Container1, LV_DIR_HOR);
lv_obj_set_style_pad_left(ui_Container1, 155, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container1, 155, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Icon_1 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_1, &ui_img_images_icons_asset_1_png);
lv_obj_set_width( ui_Icon_1, 80);
lv_obj_set_height( ui_Icon_1, 80);
lv_obj_set_align( ui_Icon_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_1, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_clear_flag( ui_Icon_1, LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_Icon_2 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_2, &ui_img_images_icons_asset_2_png);
lv_obj_set_width( ui_Icon_2, 80);
lv_obj_set_height( ui_Icon_2, 80);
lv_obj_set_align( ui_Icon_2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Icon_2, LV_STATE_FOCUSED );     /// States
lv_obj_add_flag( ui_Icon_2, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags

ui_Icon_3 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_3, &ui_img_images_icons_asset_3_png);
lv_obj_set_width( ui_Icon_3, 80);
lv_obj_set_height( ui_Icon_3, 80);
lv_obj_set_align( ui_Icon_3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_3, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags

ui_Icon_4 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_4, &ui_img_images_icons_asset_4_png);
lv_obj_set_width( ui_Icon_4, 80);
lv_obj_set_height( ui_Icon_4, 80);
lv_obj_set_align( ui_Icon_4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_4, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags

ui_Icon_5 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_5, &ui_img_images_icons_asset_5_png);
lv_obj_set_width( ui_Icon_5, 80);
lv_obj_set_height( ui_Icon_5, 80);
lv_obj_set_align( ui_Icon_5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_5, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags

ui_Icon_6 = lv_img_create(ui_Container1);
lv_img_set_src(ui_Icon_6, &ui_img_images_icons_asset_8_png);
lv_obj_set_width( ui_Icon_6, 80);
lv_obj_set_height( ui_Icon_6, 80);
lv_obj_set_align( ui_Icon_6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_6, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags


}
