// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: t-encoder

#include "../ui.h"

void ui_screen_watch_screen_init(void)
{
ui_screen_watch = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_watch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_watch, lv_color_hex(0x140E40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_watch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hour_hand = lv_img_create(ui_screen_watch);
lv_img_set_src(ui_hour_hand, &ui_img_images_watch_hour_hand_png);
lv_obj_set_width( ui_hour_hand, LV_SIZE_CONTENT);  /// 38
lv_obj_set_height( ui_hour_hand, LV_SIZE_CONTENT);   /// 123
lv_obj_set_x( ui_hour_hand, 176 );
lv_obj_set_y( ui_hour_hand, 92 );
lv_obj_add_flag( ui_hour_hand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hour_hand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_hour_hand,19,103);

ui_minute_hand = lv_img_create(ui_screen_watch);
lv_img_set_src(ui_minute_hand, &ui_img_images_watch_minute_hand_png);
lv_obj_set_width( ui_minute_hand, LV_SIZE_CONTENT);  /// 18
lv_obj_set_height( ui_minute_hand, LV_SIZE_CONTENT);   /// 204
lv_obj_set_x( ui_minute_hand, 186 );
lv_obj_set_y( ui_minute_hand, 20 );
lv_obj_add_flag( ui_minute_hand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_minute_hand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_minute_hand,9,175);

ui_second_hand = lv_img_create(ui_screen_watch);
lv_img_set_src(ui_second_hand, &ui_img_images_watch_second_hand_png);
lv_obj_set_width( ui_second_hand, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( ui_second_hand, LV_SIZE_CONTENT);   /// 227
lv_obj_set_x( ui_second_hand, 192 );
lv_obj_set_y( ui_second_hand, 8 );
lv_obj_add_flag( ui_second_hand, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_second_hand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_second_hand,3,187);

ui_Panel1 = lv_obj_create(ui_screen_watch);
lv_obj_set_width( ui_Panel1, 15);
lv_obj_set_height( ui_Panel1, 15);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000039), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



}
