// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: t-encoder

#include "../ui.h"

void ui_screen_brightness_screen_init(void)
{
ui_screen_brightness = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_brightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_brightness, lv_color_hex(0x140E40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_brightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc_brightness = lv_arc_create(ui_screen_brightness);
lv_obj_set_width( ui_Arc_brightness, 250);
lv_obj_set_height( ui_Arc_brightness, 250);
lv_obj_set_align( ui_Arc_brightness, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc_brightness, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc_brightness, 100);
lv_obj_set_style_arc_color(ui_Arc_brightness, lv_color_hex(0x230D5E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_brightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc_brightness, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc_brightness, lv_color_hex(0x6A68EF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_brightness, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc_brightness, lv_color_hex(0x6A68EF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_brightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Arc_brightness, lv_color_hex(0x0C0047), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Arc_brightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Arc_brightness, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Arc_brightness, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc_brightness, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc_brightness, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc_brightness, 10, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label_Brightness = lv_label_create(ui_screen_brightness);
lv_obj_set_width( ui_Label_Brightness, 135);
lv_obj_set_height( ui_Label_Brightness, 40);
lv_obj_set_align( ui_Label_Brightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Brightness,"100");
lv_obj_set_style_text_color(ui_Label_Brightness, lv_color_hex(0x6A68EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Brightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Brightness, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Brightness, &ui_font_ZD30, LV_PART_MAIN| LV_STATE_DEFAULT);


}
