// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: t-encoder

#ifndef _T_ENCODER_UI_H
#define _T_ENCODER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void date_Animation( lv_obj_t *TargetObject, int delay);
void temp_Animation( lv_obj_t *TargetObject, int delay);
void weather_Animation( lv_obj_t *TargetObject, int delay);
void second_Animation( lv_obj_t *TargetObject, int delay);
void minute_Animation( lv_obj_t *TargetObject, int delay);
void hour_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_screen_watch
void ui_screen_watch_screen_init(void);
extern lv_obj_t *ui_screen_watch;
extern lv_obj_t *ui_hour_hand;
extern lv_obj_t *ui_minute_hand;
extern lv_obj_t *ui_second_hand;
extern lv_obj_t *ui_Panel1;
// CUSTOM VARIABLES

// SCREEN: ui_screen_menu
void ui_screen_menu_screen_init(void);
extern lv_obj_t *ui_screen_menu;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Icon_1;
extern lv_obj_t *ui_Icon_2;
extern lv_obj_t *ui_Icon_3;
extern lv_obj_t *ui_Icon_4;
extern lv_obj_t *ui_Icon_5;
extern lv_obj_t *ui_Icon_6;
// CUSTOM VARIABLES

// SCREEN: ui_screen_brightness
void ui_screen_brightness_screen_init(void);
extern lv_obj_t *ui_screen_brightness;
extern lv_obj_t *ui_Arc_brightness;
extern lv_obj_t *ui_Label_Brightness;
// CUSTOM VARIABLES

// SCREEN: ui_screen_weather
void ui_screen_weather_screen_init(void);
void ui_event_screen_weather( lv_event_t * e);
extern lv_obj_t *ui_screen_weather;
extern lv_obj_t *ui_Label_temp;
extern lv_obj_t *ui_Icon_weather;
extern lv_obj_t *ui_Label_date;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_images_watch_hour_hand_png);   // assets/Images/watch/hour_hand.png
LV_IMG_DECLARE( ui_img_images_watch_minute_hand_png);   // assets/Images/watch/minute_hand.png
LV_IMG_DECLARE( ui_img_images_watch_second_hand_png);   // assets/Images/watch/second_hand.png
LV_IMG_DECLARE( ui_img_images_icons_asset_1_png);   // assets/Images/icons/Asset 1.png
LV_IMG_DECLARE( ui_img_images_icons_asset_2_png);   // assets/Images/icons/Asset 2.png
LV_IMG_DECLARE( ui_img_images_icons_asset_3_png);   // assets/Images/icons/Asset 3.png
LV_IMG_DECLARE( ui_img_images_icons_asset_4_png);   // assets/Images/icons/Asset 4.png
LV_IMG_DECLARE( ui_img_images_icons_asset_5_png);   // assets/Images/icons/Asset 5.png
LV_IMG_DECLARE( ui_img_images_icons_asset_8_png);   // assets/Images/icons/Asset 8.png
LV_IMG_DECLARE( ui_img_images_icons_asset_10_png);   // assets/Images/icons/Asset 10.png

// FONTS
LV_FONT_DECLARE( ui_font_ZD100);
LV_FONT_DECLARE( ui_font_ZD30);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
